import {BaseUtils} from './base-utils';

describe('Test Base utils', () => {

    it('Test text utils:  ', () => {
        const base64 = 'Dw4VEw0TDA8NFRESDQ0VEBUVEzckIyUeEwUGBQYGBgsKCwwpLDEyKiYEDj8JGjMqQDEvIBIHCwcKCQkLCggIDC8pIRwYDgsNCgoHFRoZFxMYHRweJCUjHykkHiIKAgEBBQYGBQUDBwYKCgMDBQU' +
            'ICQsgGwUDAQESHQUkDQgNDQsMDAgGBQcPEgMFBAcLCAcHCwcFBgYICQ8VFhoYGhEKCwsPDhYiISgpJi8vLCYpJBATDQ8REgwLEA0KEQ8MCxEMDAQKCgoHDQwPCwIFBQUFBQQEBAQFDhgWEhEUFBQQGxYLEQ0qHxI' +
            'mFQ0mIA8qGxIOEBURExEZFSgYGxgQFRQYDBUPKCMTKRcPJyIWKx0FEBYaDAwNEA0SDRkUGAsPCw4MDw8MDRIMCxYUERcJDAsKBRQLCB8dGxUOExYWFhkmGSAaFBoQFw4KDg4ODBIjGQcREA0LGB8WFwsKDwkNCw' +
            'cMHBUVDg8OEBMSGBoRGhETDwkPBwkKCwoQFBcUCQ0OCRAcGBcKCwsJBRQKCRUcGxoLERMTFhUfHx8jGB4ZHCMhIxUyJSQmIxcKDAoMBwgHDgkLCQoMAwsGAhEHEQQOGg4TFg0ZExQNDAwMCg4ODhIbDgsKEwwOC' +
            'hEJFAYNHg0YFhIYFxENDBEPDA8XCxMeEREUDhYTEBAFCQ0LCQgIEA0JCwsMDAgMEggLDQoJDQ4GCgsFChMXERIWFBATEhIaFxgTGxMdEiMSEhsbGBISBxQRFhcYEw8KGBYfGQUNCBEQFxEMDQ4QExEQEhMSExEVH' +
            'AUPDxITCAUFBAMDBQ0PEA4SIgkLEQ8RFA8OECAfFhQREBAYGx0fGhocIB8hIBshGCAYFRgvLyoiJBkZFwkHBw0mKyopKhkICxIICQoHCAwGBgoLCw0VCQgECwwMEgsLEA4RExMUEBERDQ4XDxYWGBYYExgeJR4N' +
            'DQoOFAkODxAQGBcRERENBhESEBYZGRUZGBshJyQZEREPFBINEA0OCw8NDBQNBgcRFR0dIxoaDw8SEBAPEBIRFR0hHRkgISMYFxUgKykhJg0KIR0aHw8aHBUiGB8aKiIeFCEaHRITEhwhGAIREA8PECEiFQ8NDhY' +
            'QExQWHxUWJSMeIiAOERcTHRMWFRUaFBMJDgoIGxgIBwYMHBMTGhAiExAYERcUEggTHQ0GBgQKDw8QDwsPEg8QDhUXFA4WEQoKBwwSFh0aAyAXBwYHCSIGGwkRFxEQEw8SEBEVESUdIBAUGhMXGBwYDRQXNS8pKys' +
            'PGQwbCQ8YEhEVFBQUDSsRHw4QHhEfFyEkFhYbOCsrJCoOCBIcJB0rFR0hJxsbHR0ZIBsfKyIJFgQFBwkFDAoKDwsJCBIYFBYaHBYHChcLDA8LEg8WDggFBQUDBQQLDwwLCwoLBw0ODAoNCwgNCwoOEgwNCw4TCgg' +
            'QFiEdFAcJChIlFA8VGBclDxITFCMVHhAbHiEgJRoHCQ4KIRQVFB8ZJhQYHxonFiMSJyYjIyUhBgkQBxAOCgoKHhooEhcjIBUbIB8FHTsREQcNFRMKGRkVFyApKSEnHg4dHRYbFBUeIhMOHRsVFh0sKigiHCcHBAM' +
            'eBwgJCRAVGCIcCwMEAwQkJBUYGS0XFS0fFh0xHhwkIx8WKgsZKBcLFggMCTIICwsNBx0qEQoCEQ4QDgsMEREVGBcVGRIdHhcvHyIhHCwsNSMaJSsdJSUcGQ0IBwQECw0PGhEREhYSFywbHS8hGSAnUQ8WJSAdGhgc' +
            'IzEWGxgdHyYsPTEgFx4SHx0iKSIfGy4qICcvIiIhIiITGhwRExkkISotJjI0LkE8Pzs8OElPPUNBSjtAOT88NTIuEQsODQoMEAwLCwoNDAkODAoNCgsODAoODAsHEw0SDA4LDhISFQ8PExgJCQcLChMMBQgJDgsTG' +
            'BMRCQYGCAkFChERGg4REhAJCQUQBw0UBgQLBw8MGREZDQ0GBgcKCAIODQoQEAwGDAsDBQQFBQoMBggNDQ0EDQcEBAIKDwoQGQkLDgsKERAMEQ0GDw4NGhIPBhIMEBYWDREUBA0NDRwQEQkYEgsSFBALFBUPExIOFh' +
            'cIFwkMAQoHDQ4UFRITKhwnHRwUFBQTERsTFB0ZJBQTFRYYJh8tJA8fCygaIBoVHhsdHxwmJSI+OzAqJR0UExMWDhISERUZFRESFhAEBgUGBwUKCw4JDQ8QEhofIiYsIBsyHxghIxUUFBodICsgHyQkBg8XIxYjFx4' +
            'sISQgJyklKSYbFRgeLCodGzMvGSUbISIfEw8oIyIWFDEiEBwhKiUYJiI1IxggGRgRBwMULRYgLCEcKRkbJRgvFyEjLB8wID8jGysOFiYjMw8UGSEuHBgfFBkWHxEYKx0xHR0UHyEXFRgbJiIVHxwgLiMiHCQgFhUc' +
            'IhwjJxwrHQ0LCQsOBg0KCA8ICQ8KCQUNEA8SDRANEAwLCw0JCQ4EBAMEAwMDAwUEBAMFBwcDBQcIBQIEBgQEBAcgLxcRBxAaFgkGHRcOHRILBggVCwcCBQkJCQwNCgcHCwwcGRYLCRkXFAwNIwsQIBYNCQgkEw4DA' +
            'wUIBwcHCQsIBAgNIBAQHhEJAgMCAgICAgIDAwMDBAMUDxEQDw8RDAYNDAgHDwoHCAoIBxIUEAkUDhAKDQ4cDRQICxwWDRsUFg0NDBQaIS8nLTAsIxMYCxARExcULjMpJzY0KSoxMywiKzIrLjY1PCwnGBAXEw8UCg' +
            'oREQwOEhQPDxANEg0HAA==';
        const base64Atob = BaseUtils.base64DecToArr(base64);
        expect(base64Atob).toBeTruthy();
    });
});


