import { ElementRef } from '@angular/core';
import { TranscriptionPluginComponent } from './transcription-plugin.component';

describe('TranscriptionPluginComponent automatic synchronization', () => {
    function createComponent() {
        const component = new TranscriptionPluginComponent({} as any);
        component.pluginConfiguration = {
            data: {
                ...component.getDefaultConfig().data,
                tcIn: 0
            }
        } as any;
        return component;
    }

    function setOutOfViewSelection(component: TranscriptionPluginComponent): void {
        const container = document.createElement('div');
        container.innerHTML = `
            <div class="segment">
                <div class="subsegment">
                    <div class="text"><span class="w selected"></span></div>
                </div>
            </div>`;
        const selectedWord = container.querySelector('.w.selected') as HTMLElement;
        component.transcriptionElement = new ElementRef(container);
        component.autoScroll = true;
        spyOn(container, 'getBoundingClientRect').and.returnValue({ top: 100 } as DOMRect);
        spyOn(selectedWord, 'getBoundingClientRect').and.returnValue({ top: 10 } as DOMRect);
        Object.defineProperty(selectedWord, 'clientHeight', { value: 10, configurable: true });
        Object.defineProperty(container, 'clientHeight', { value: 50, configurable: true });
    }

    afterEach(() => {
        jasmine.clock().uninstall();
    });

    it('uses the SEEKING candidate time with the configured tcIn offset', () => {
        const component = createComponent();
        component.pluginConfiguration.data.tcIn = 10;
        component.transcriptionElement = null;

        (component as any).handleSeekingEvent(25);

        expect(component.currentTime).toBe(35);
    });

    it('ignores the scroll event generated by automatic synchronization', () => {
        const component = createComponent();
        const updateSpy = spyOn(component, 'updateSynchro');
        (component as any).isAutoScrolling = true;

        component.handleScroll();

        expect((component as any).isAutoScrolling).toBeFalse();
        expect(updateSpy).not.toHaveBeenCalled();
    });

    it('recenters an out-of-view selection after the auto-sync delay', () => {
        const component = createComponent();
        setOutOfViewSelection(component);
        const scrollSpy = spyOn(component, 'scrollToSelectedSegment');
        jasmine.clock().install();

        component.updateSynchro();
        jasmine.clock().tick(TranscriptionPluginComponent.AUTO_SYNC_DELAY - 1);
        expect(scrollSpy).not.toHaveBeenCalled();
        jasmine.clock().tick(1);

        expect(scrollSpy).toHaveBeenCalled();
    });

    it('postpones auto-sync while the user is interacting', () => {
        const component = createComponent();
        setOutOfViewSelection(component);
        const scrollSpy = spyOn(component, 'scrollToSelectedSegment');
        jasmine.clock().install();

        component.updateSynchro();
        jasmine.clock().tick(TranscriptionPluginComponent.AUTO_SYNC_DELAY - 1);
        component.resetAutoSyncTimer();
        jasmine.clock().tick(1);
        expect(scrollSpy).not.toHaveBeenCalled();
        jasmine.clock().tick(TranscriptionPluginComponent.AUTO_SYNC_DELAY - 1);

        expect(scrollSpy).toHaveBeenCalled();
    });

    it('does not start auto-sync when synchronization is inactive', () => {
        const component = createComponent();
        const scrollSpy = spyOn(component, 'scrollToSelectedSegment');
        component.displaySynchro.set(false);
        jasmine.clock().install();

        component.resetAutoSyncTimer();
        jasmine.clock().tick(TranscriptionPluginComponent.AUTO_SYNC_DELAY);

        expect(scrollSpy).not.toHaveBeenCalled();
    });

    it('cancels a pending recenter when the component is destroyed', () => {
        const component = createComponent();
        setOutOfViewSelection(component);
        const scrollSpy = spyOn(component, 'scrollToSelectedSegment');
        jasmine.clock().install();

        component.updateSynchro();
        component.ngOnDestroy();
        jasmine.clock().tick(TranscriptionPluginComponent.AUTO_SYNC_DELAY);

        expect(scrollSpy).not.toHaveBeenCalled();
    });
});
